# Generated by Django 2.2 on 2020-08-08 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login_app', '0006_auto_20200808_1238'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('tag_line', models.CharField(help_text='Provide a short description (e.g., <em>Learn to build beautiful photo albums for gifts or to sell</em>).', max_length=255)),
                ('date', models.DateTimeField(help_text='Please use the following format: <em>YYYY-MM-DD</em>.')),
                ('description', models.TextField()),
                ('location', models.CharField(help_text='For virtual classes, use the videoconference link; for recorded courses, use the YouTube or video link; for in-person courses, use the address.', max_length=255)),
                ('location_type', models.CharField(choices=[('I', 'In-Person'), ('V', 'Virtual'), ('R', 'Recorded')], default='V', max_length=1)),
                ('max_size', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('areas_of_interest', models.ManyToManyField(null=True, related_name='related_courses', to='login_app.User')),
                ('attendees', models.ManyToManyField(null=True, related_name='courses_attended', to='login_app.User')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses_created', to='login_app.User')),
                ('favorited_by', models.ManyToManyField(null=True, related_name='favorite_courses', to='login_app.User')),
            ],
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255)),
                ('answer', models.CharField(blank=True, max_length=255)),
                ('answerer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions_answered', to='login_app.User')),
                ('asker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions_asked', to='login_app.User')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='classes.Course')),
            ],
        ),
    ]
