# Generated by Django 2.2 on 2020-08-08 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='areas_of_interest',
            field=models.ManyToManyField(related_name='related_courses', to='classes.Interest'),
        ),
        migrations.AlterField(
            model_name='course',
            name='attendees',
            field=models.ManyToManyField(related_name='courses_attended', to='login_app.User'),
        ),
        migrations.AlterField(
            model_name='course',
            name='favorited_by',
            field=models.ManyToManyField(related_name='favorite_courses', to='login_app.User'),
        ),
    ]
