# Generated by Django 2.2 on 2020-08-10 17:55

from django.db import migrations, models
import django.db.models.deletion
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0007_auto_20200809_2143'),
        ('classes', '0002_auto_20200808_1302'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=255)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('state', localflavor.us.models.USStateField(blank=True, max_length=2)),
                ('bio', models.TextField(blank=True)),
                ('birth_date', models.DateTimeField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('areas_of_interest', models.ManyToManyField(related_name='related_profiles', to='classes.Interest')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='login_app.User')),
            ],
        ),
    ]
