# Generated by Django 2.2 on 2020-08-15 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_auto_20200810_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='areas_of_interest',
            field=models.ManyToManyField(blank=True, null=True, related_name='related_profiles', to='classes.Interest'),
        ),
    ]
