# Generated by Django 2.2 on 2020-08-15 18:58

import classes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0005_auto_20200815_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to=classes.models.user_directory_path),
        ),
    ]
