# Generated by Django 2.2 on 2020-08-15 20:48

import classes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0006_userprofile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='C:\\Users\\shari\\OneDrive\\Documents\\Coding Dojo\\python_stack\\django\\django_orm\\icraft\\media\\blank-user.jpg', null=True, upload_to=classes.models.user_directory_path),
        ),
    ]
