# Generated by Django 2.2 on 2020-08-15 21:09

import classes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0007_auto_20200815_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(default='C:\\Users\\shari\\OneDrive\\Documents\\Coding Dojo\\python_stack\\django\\django_orm\\icraft\\media\\blank-user.jpg', upload_to=classes.models.user_directory_path),
        ),
    ]
