# Generated by Django 2.2 on 2020-08-15 23:29

import classes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0011_auto_20200815_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='profile_pic',
            field=models.ImageField(blank=True, default='courses/blank-course.jpg', null=True, upload_to=classes.models.course_directory_path),
        ),
    ]
