# Generated by Django 2.2 on 2020-08-17 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0014_auto_20200817_0247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='number_of_stars',
            field=models.IntegerField(choices=[(1, 'It was awful!'), (2, 'Not so great.'), (3, 'Just Ok.'), (4, 'I liked it!'), (5, 'Pretty freakin awesome!')]),
        ),
    ]
