# Generated by Django 2.2 on 2020-08-10 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_auto_20200808_1302'),
        ('login_app', '0006_auto_20200808_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='areas_of_interest',
            field=models.ManyToManyField(related_name='interested_users', to='classes.Interest'),
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(default='Missing'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
